# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'
use_frameworks!

target 'EZHack' do
    pod 'GoogleMaps'
    pod 'GooglePlaces'
    pod 'fluid-slider'
    pod 'M13Checkbox'

end
